# Generated by Django 5.2.5 on 2025-08-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(max_length=64)),
                ('orcid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('affiliations', models.JSONField(blank=True, default=list)),
                ('email_domains', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=256)),
                ('doi', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('url', models.TextField(blank=True)),
                ('source', models.CharField(max_length=32)),
                ('score', models.FloatField(default=0.0)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('task_ref', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('job_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('hints', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='running', max_length=16)),
                ('progress', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
