# Generated by Django 5.2.5 on 2025-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
